# Generated by Django 4.2.2 on 2023-06-20 13:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='information',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
